/**
 * Pure annotation text rendering boundary.
 *
 * This module normalizes copied text, renders Markdown and optional math, then
 * sanitizes generated HTML. It does not read or mutate Zotero Reader DOM.
 */
import createDOMPurify, { type WindowLike } from "dompurify";
import MarkdownIt from "markdown-it";
import markdownItTexmath from "markdown-it-texmath";

import type { MarkdownRenderer } from "./types.js";

interface MathPluginOptions {
  delimiters?: string[];
}

type MathPlugin = (markdown: MarkdownEngine, options?: MathPluginOptions) => unknown;

interface MarkdownEngine {
  render(source: string): string;
  use(plugin: MathPlugin, options?: MathPluginOptions): unknown;
}

interface CreateMarkdownRendererOptions {
  markdown?: MarkdownEngine;
  mathMarkdown?: MarkdownEngine;
  mathPlugin?: MathPlugin | null;
  mathPluginOptions?: MathPluginOptions;
  isMathEnabled?: () => boolean;
  windowRef?: Window | null;
}

// Raw annotation HTML stays disabled, while DOMPurify remains the final boundary
// for HTML generated by Markdown plugins such as texmath.
const DEFAULT_MARKDOWN_OPTIONS = {
  html: false,
  breaks: true,
  linkify: true,
  typographer: false
};

// Keep DOMPurify's default safe schemes and preserve the read/navigation URI
// families handled by Weavero. Other zotero: actions remain plain text.
const SAFE_URI_PATTERN = /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|sms|cid|xmpp|matrix):|zotero:\/\/(?:select|open(?:-pdf)?|note)\/|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i;

/**
 * Creates a renderer with separate plain and math-capable Markdown engines so
 * toggling math never leaves texmath rules attached to the plain path.
 */
export function createMarkdownRenderer({
  markdown,
  mathMarkdown,
  mathPlugin = markdownItTexmath,
  mathPluginOptions = { delimiters: ["dollars", "brackets"] },
  isMathEnabled = () => true,
  windowRef = globalThis.window
}: CreateMarkdownRendererOptions = {}): MarkdownRenderer {
  const plainMarkdown = markdown ?? createDefaultMarkdownEngine();
  // Separate default engines let math be disabled again after the plugin has
  // been loaded without leaving texmath rules attached to the plain renderer.
  const mathCapableMarkdown = mathMarkdown ?? (
    markdown ? plainMarkdown : createDefaultMarkdownEngine()
  );
  const purifier = createPurifier(windowRef);
  let mathPluginLoaded = false;

  return {
    render(source: unknown): string {
      const text = normalizeMathDelimiters(String(source ?? ""));

      try {
        const html = getMarkdownForSource(text).render(text);
        return purifier
          ? purifier.sanitize(html, { ALLOWED_URI_REGEXP: SAFE_URI_PATTERN })
          : html;
      } catch {
        // A malformed plugin input must not break Zotero's reader lifecycle.
        return escapePlainText(text);
      }
    }
  };

  function getMarkdownForSource(text: string): MarkdownEngine {
    if (!mathPlugin || !isMathEnabled() || !hasMathSyntax(text)) {
      return plainMarkdown;
    }

    // Loading texmath on demand avoids changing the common plain-Markdown path
    // until a comment actually contains supported math delimiters.
    if (!mathPluginLoaded) {
      if (mathPluginOptions === undefined) {
        mathCapableMarkdown.use(mathPlugin);
      } else {
        mathCapableMarkdown.use(mathPlugin, mathPluginOptions);
      }
      mathPluginLoaded = true;
    }

    return mathCapableMarkdown;
  }
}

function createDefaultMarkdownEngine(): MarkdownIt {
  const markdown = new MarkdownIt(DEFAULT_MARKDOWN_OPTIONS);
  markdown.linkify.add("zotero:", "http:");
  return markdown;
}

function createPurifier(windowRef: Window | null): ReturnType<typeof createDOMPurify> | null {
  if (!windowRef?.document) {
    return null;
  }

  // DOMPurify and lib.dom currently describe Trusted Types with incompatible
  // generic shapes even though both receive the same browser Window at runtime.
  return createDOMPurify(windowRef as unknown as WindowLike);
}

function hasMathSyntax(text: string): boolean {
  return /(?:^|[^\\])\$\$[\s\S]+?\$\$/.test(text) ||
    /(?:^|[^\\])\$[^$\n]+?\$/.test(text) ||
    /\\\([\s\S]+?\\\)/.test(text) ||
    /\\\[[\s\S]+?\\\]/.test(text);
}

function normalizeMathDelimiters(text: string): string {
  // Zotero comments may carry CRLF or non-breaking-space indentation after
  // copy/paste; normalize both before Markdown block parsing.
  const normalizedLineEndings = text
    .replaceAll("\r\n", "\n")
    .replaceAll("\r", "\n");

  const normalizedWhitespace = normalizedLineEndings
    .replace(/[\u00a0\u202f]/g, " ");

  const normalizedDelimiters = normalizedWhitespace
    .replace(/(^|\n)([ \t]*)\\\\\[[ \t]*(?=\n|$)/g, "$1$2\\[")
    .replace(/(^|\n)([ \t]*)\\\\\][ \t]*(?=\n|$)/g, "$1$2\\]");

  return isolateBracketDisplayMath(normalizedDelimiters);
}

function isolateBracketDisplayMath(text: string): string {
  const lines = text.split("\n");
  const output: string[] = [];

  lines.forEach((line, index) => {
    // Bracket display math needs block boundaries when copied directly next to
    // prose, but indentation must remain intact for list items.
    if (isBracketMathOpeningLine(line) && output.length > 0 && output[output.length - 1].trim() !== "") {
      output.push("");
    }

    output.push(line);

    const nextLine = lines[index + 1];
    if (isBracketMathClosingLine(line) && nextLine !== undefined && nextLine.trim() !== "") {
      output.push("");
    }
  });

  return output.join("\n");
}

function isBracketMathOpeningLine(line: string): boolean {
  return /^[ \t]*\\\[[ \t]*$/.test(line);
}

function isBracketMathClosingLine(line: string): boolean {
  return /^[ \t]*\\\][ \t]*$/.test(line);
}

function escapePlainText(text: string): string {
  return text
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;")
    .replaceAll("\r\n", "\n")
    .replaceAll("\r", "\n")
    .replaceAll("\n", "<br>");
}
