/**
 * Pure annotation text rendering boundary.
 *
 * This module normalizes copied text, renders Markdown and optional math, then
 * sanitizes generated HTML. It does not read or mutate Zotero Reader DOM.
 */
import createDOMPurify, { type WindowLike } from "dompurify";
import MarkdownIt from "markdown-it";
import markdownItCjkFriendly from "markdown-it-cjk-friendly";
import markdownItMark from "markdown-it-mark";
import markdownItTexmath from "markdown-it-texmath";

import markdownItMarkColors from "./markdown-it-mark-colors.js";
import { createSvgRenderer } from "./svg-renderer.js";
import type { MarkdownRenderer } from "./types.js";
import type { MathOutput } from "./settings.js";

interface MathPluginOptions {
  delimiters?: string[];
  katexOptions?: { output?: MathOutput };
}

type MathPlugin = (markdown: MarkdownEngine, options?: MathPluginOptions) => unknown;

interface MarkdownEngine {
  render(source: string): string;
  use(plugin: MathPlugin, options?: MathPluginOptions): unknown;
}

interface CreateMarkdownRendererOptions {
  markdown?: MarkdownEngine;
  mathMarkdown?: MarkdownEngine;
  mathPlugin?: MathPlugin | null;
  mathPluginOptions?: MathPluginOptions;
  isMathEnabled?: () => boolean;
  isSvgEnabled?: () => boolean;
  getMathOutput?: () => MathOutput;
  windowRef?: Window | null;
}

// Raw annotation HTML stays disabled, while DOMPurify remains the final boundary
// for HTML generated by Markdown plugins such as texmath.
const DEFAULT_MARKDOWN_OPTIONS = {
  html: false,
  breaks: true,
  linkify: true,
  typographer: false
};

// Keep DOMPurify's default safe schemes and preserve the read/navigation URI
// families handled by Weavero. Other zotero: actions remain plain text.
const SAFE_URI_PATTERN = /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|sms|cid|xmpp|matrix):|zotero:\/\/(?:select|open(?:-pdf)?|note)\/|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i;

/**
 * Creates a renderer with separate plain and math-capable Markdown engines so
 * toggling math never leaves texmath rules attached to the plain path.
 */
export function createMarkdownRenderer({
  markdown,
  mathMarkdown,
  mathPlugin = markdownItTexmath,
  mathPluginOptions = { delimiters: ["dollars", "brackets"] },
  getMathOutput = () => mathPluginOptions?.katexOptions?.output ?? "htmlAndMathml",
  isMathEnabled = () => true,
  isSvgEnabled = () => false,
  windowRef = globalThis.window
}: CreateMarkdownRendererOptions = {}): MarkdownRenderer {
  const renderSvg = createSvgRenderer(windowRef);
  const plainMarkdown = markdown ?? createDefaultMarkdownEngine(isSvgEnabled, renderSvg);
  // Separate default engines let math be disabled again after the plugin has
  // been loaded without leaving texmath rules attached to the plain renderer.
  const mathCapableMarkdown = mathMarkdown ?? (
    markdown ? plainMarkdown : createDefaultMarkdownEngine(isSvgEnabled, renderSvg)
  );
  const purifier = createPurifier(windowRef);
  // texmath retains this options object, so live switches do not rebuild its rules.
  const katexOptions = { ...mathPluginOptions?.katexOptions };
  const configuredMathOptions = { ...mathPluginOptions, katexOptions };
  let mathPluginLoaded = false;

  return {
    render(source: unknown): string {
      const text = normalizeMathDelimiters(String(source ?? ""));
      const mathmlOnly = getMathOutput() === "mathml";
      katexOptions.output = mathmlOnly ? "mathml" : "htmlAndMathml";

      try {
        const generated = getMarkdownForSource(text).render(text);
        const html = mathmlOnly ? wrapMathmlDisplayMath(generated) : generated;
        return purifier
          ? purifier.sanitize(html, {
            ALLOWED_URI_REGEXP: SAFE_URI_PATTERN,
            // Native MathML needs semantics intact; unwrapping annotation exposes TeX.
            ...(mathmlOnly ? { ADD_TAGS: ["semantics", "annotation"], ADD_ATTR: ["encoding"] } : {})
          })
          : html;
      } catch {
        // A malformed plugin input must not break Zotero's reader lifecycle.
        return escapePlainText(text);
      }
    }
  };

  function getMarkdownForSource(text: string): MarkdownEngine {
    if (!mathPlugin || !isMathEnabled() || !hasMathSyntax(text)) {
      return plainMarkdown;
    }

    // Loading texmath on demand avoids changing the common plain-Markdown path
    // until a comment actually contains supported math delimiters.
    if (!mathPluginLoaded) {
      if (mathPluginOptions === undefined) {
        mathCapableMarkdown.use(mathPlugin);
      } else {
        mathCapableMarkdown.use(mathPlugin, configuredMathOptions);
      }
      mathPluginLoaded = true;
    }

    return mathCapableMarkdown;
  }
}

function wrapMathmlDisplayMath(html: string): string {
  // KaTeX's MathML-only branch omits the display wrapper used by our scroller.
  return html.replace(
    /<span class="katex">(<math\b[^>]*\bdisplay="block"[^>]*>[\s\S]*?<\/math>)<\/span>/g,
    '<span class="katex-display"><span class="katex">$1</span></span>'
  );
}

function createDefaultMarkdownEngine(isSvgEnabled: () => boolean, renderSvg: ReturnType<typeof createSvgRenderer>): MarkdownIt {
  const markdown = new MarkdownIt(DEFAULT_MARKDOWN_OPTIONS);
  markdown.use(markdownItCjkFriendly);
  markdown.use(markdownItMark);
  markdown.use(markdownItMarkColors);
  markdown.linkify.add("zotero:", "http:");
  const originalFence = markdown.renderer.rules.fence!;
  markdown.renderer.rules.fence = (tokens, index, options, env, self) => {
    const fallback = originalFence(tokens, index, options, env, self);
    const language = tokens[index].info.trim().toLowerCase();
    if (!isSvgEnabled() || (language && language !== "svg")) return fallback;
    return renderSvg(tokens[index].content, fallback, { inferFromSource: !language });
  };
  return markdown;
}

function createPurifier(windowRef: Window | null): ReturnType<typeof createDOMPurify> | null {
  if (!windowRef?.document) {
    return null;
  }

  // DOMPurify and lib.dom currently describe Trusted Types with incompatible
  // generic shapes even though both receive the same browser Window at runtime.
  return createDOMPurify(windowRef as unknown as WindowLike);
}

function hasMathSyntax(text: string): boolean {
  return /(?:^|[^\\])\$\$[\s\S]+?\$\$/.test(text) ||
    /(?:^|[^\\])\$[^$\n]+?\$/.test(text) ||
    /\\\([\s\S]+?\\\)/.test(text) ||
    /\\\[[\s\S]+?\\\]/.test(text);
}

function normalizeMathDelimiters(text: string): string {
  // Zotero comments may carry CRLF or non-breaking-space indentation after
  // copy/paste; normalize both before Markdown block parsing.
  const normalizedLineEndings = text
    .replaceAll("\r\n", "\n")
    .replaceAll("\r", "\n");

  // Code fences are literal source; formula normalization must not rewrite SVG
  // labels, whitespace or attributes before the SVG fence renderer reads them.
  if (normalizedLineEndings.includes("```") || normalizedLineEndings.includes("~~~")) {
    const output: string[] = [];
    let plain: string[] = [];
    let fence: { marker: string; length: number } | null = null;
    const flushPlain = () => {
      if (plain.length) output.push(normalizeNonCodeMathDelimiters(plain.join("\n")));
      plain = [];
    };
    for (const line of normalizedLineEndings.split("\n")) {
      const content = splitMarkdownBlockPrefix(line.replace(/[\u00a0\u202f]/g, " ")).content;
      const marker = content.match(/^(`{3,}|~{3,})(.*)$/);
      if (fence) {
        output.push(line);
        if (marker && marker[1][0] === fence.marker && marker[1].length >= fence.length && !marker[2].trim()) fence = null;
      } else if (marker) {
        flushPlain(); output.push(line);
        fence = { marker: marker[1][0], length: marker[1].length };
      } else {
        plain.push(line);
      }
    }
    flushPlain();
    return output.join("\n");
  }
  return normalizeNonCodeMathDelimiters(normalizedLineEndings);
}

function normalizeNonCodeMathDelimiters(normalizedLineEndings: string): string {

  const normalizedWhitespace = normalizedLineEndings
    .replace(/[\u00a0\u202f]/g, " ");

  const normalizedDelimiters = normalizedWhitespace
    .replace(/(^|\n)([ \t]*)\\\\\[[ \t]*(?=\n|$)/g, "$1$2\\[")
    .replace(/(^|\n)([ \t]*)\\\\\][ \t]*(?=\n|$)/g, "$1$2\\]");

  return isolateDollarDisplayMathTrailingText(
    isolateBracketDisplayMath(normalizedDelimiters)
  );
}

function isolateDollarDisplayMathTrailingText(text: string): string {
  if (!text.includes("$$")) {
    return text;
  }

  const lines = text.split("\n");
  const output: string[] = [];
  let displayMathOpen = false;
  let fence: { marker: string; length: number } | null = null;

  for (const line of lines) {
    const parts = splitMarkdownBlockPrefix(line);

    if (!displayMathOpen) {
      if (fence) {
        const closingFence = parts.content.match(/^(`{3,}|~{3,})[ \t]*$/);
        output.push(line);
        if (
          closingFence &&
          closingFence[1][0] === fence.marker &&
          closingFence[1].length >= fence.length
        ) {
          fence = null;
        }
        continue;
      }

      const fenceMatch = parts.content.match(/^(`{3,}|~{3,})/);
      if (fenceMatch) {
        fence = { marker: fenceMatch[1][0], length: fenceMatch[1].length };
        output.push(line);
        continue;
      }

      if (!parts.content.startsWith("$$")) {
        output.push(line);
        continue;
      }

      const closingIndex = findDollarDisplayClosingDelimiter(parts.content, 2);
      if (closingIndex === -1) {
        displayMathOpen = true;
        output.push(line);
        continue;
      }

      appendDollarDisplayLine(output, parts, closingIndex);
      continue;
    }

    const closingIndex = findDollarDisplayClosingDelimiter(parts.content, 0);
    if (closingIndex === -1) {
      output.push(line);
      continue;
    }

    appendDollarDisplayLine(output, parts, closingIndex);
    displayMathOpen = false;
  }

  return output.join("\n");
}

interface MarkdownBlockLineParts {
  prefix: string;
  continuationPrefix: string;
  content: string;
}

function splitMarkdownBlockPrefix(line: string): MarkdownBlockLineParts {
  const match = line.match(
    /^([ \t]{0,3})((?:>[ \t]?)*)(?:((?:[-+*]|\d+[.)]))([ \t]+))?(.*)$/
  );

  if (!match) {
    return { prefix: "", continuationPrefix: "", content: line };
  }

  const [, indentation, quotePrefix, listMarker = "", listSpacing = "", content] = match;
  const listPrefix = `${listMarker}${listSpacing}`;

  return {
    prefix: `${indentation}${quotePrefix}${listPrefix}`,
    continuationPrefix: `${indentation}${quotePrefix}${" ".repeat(listPrefix.length)}`,
    content
  };
}

function findDollarDisplayClosingDelimiter(content: string, start: number): number {
  let index = content.indexOf("$$", start);

  while (index !== -1) {
    if (index === 0 || content[index - 1] !== "\\") {
      return index;
    }
    index = content.indexOf("$$", index + 2);
  }

  return -1;
}

function appendDollarDisplayLine(
  output: string[],
  parts: MarkdownBlockLineParts,
  closingIndex: number
): void {
  let mathEnd = closingIndex + 2;
  const equationNumber = parts.content.slice(mathEnd).match(/^[ \t]*\([^\s)]+\)/);
  if (equationNumber) {
    mathEnd += equationNumber[0].length;
  }

  const trailingText = parts.content.slice(mathEnd);
  if (trailingText.trim() === "") {
    output.push(`${parts.prefix}${parts.content}`);
    return;
  }

  output.push(`${parts.prefix}${parts.content.slice(0, mathEnd)}`);
  output.push(`${parts.continuationPrefix}${trailingText.trimStart()}`);
}

function isolateBracketDisplayMath(text: string): string {
  const lines = text.split("\n");
  const output: string[] = [];

  lines.forEach((line, index) => {
    // Bracket display math needs block boundaries when copied directly next to
    // prose, but indentation must remain intact for list items.
    if (isBracketMathOpeningLine(line) && output.length > 0 && output[output.length - 1].trim() !== "") {
      output.push("");
    }

    output.push(line);

    const nextLine = lines[index + 1];
    if (isBracketMathClosingLine(line) && nextLine !== undefined && nextLine.trim() !== "") {
      output.push("");
    }
  });

  return output.join("\n");
}

function isBracketMathOpeningLine(line: string): boolean {
  return /^[ \t]*\\\[[ \t]*$/.test(line);
}

function isBracketMathClosingLine(line: string): boolean {
  return /^[ \t]*\\\][ \t]*$/.test(line);
}

function escapePlainText(text: string): string {
  return text
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;")
    .replaceAll("\r\n", "\n")
    .replaceAll("\r", "\n")
    .replaceAll("\n", "<br>");
}
